[project]

dependencies = [
    "pycdo @ file:///${PROJECT_ROOT}/python/pycdo",
]
requires-python = "==3.12.*"

[tool.pdm]
distribution = false

# We use ruff for linting:
[tool.ruff]
line-length = 100
