# These are all command services that perform our git hooks within the container

services:
  git-pre-commit: &command-base
    extends:
      file: docker-compose.dashboard.yml
      service: web
    command: /bin/bash -l -c './docker/developers/run.sh ./tools/hooks/pre-commit'
