name: Workflow to analyze i18n sync PRs
on:
  push:
    paths:
    - '.github/workflows/**'
    - 'bin/i18n/analyze_pr.rb'
  workflow_dispatch:
    inputs:
      name:
        description: 'a person'
        required: true
        default: 'ha nguyen'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello ${{ github.event.inputs.name }}!"
  run_my_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: My first step
        id: my_action
        uses: ./.github/actions/my_action
        with:
          who-to-greet: 'ha nguyen'
      - name: Get the output time
        run: echo "The time was ${{ steps.my_action.outputs.time }}"
