name: Warn on PR's that modify DMS tasks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check for modified files
      id: check_files
      uses: actions/github-script@v7
      with:
        script: |
          const prFiles = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          console.log(prFiles.data);
          console.log("found", prFiles.data.some(file => file.filename == 'aws/dms/tasks.yml'));
          const fileModified = prFiles.data.some(file => file.filename == 'aws/dms/tasks.yml');
          return { file_modified: fileModified };

    - name: Add comment to PR
      if: steps.check_files.outputs.file_modified == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "This PR modifies the `aws/dms/tasks.yml` file. These changes must be deployed manually by the Infra team before merging."
          })
